{"errorMessage": "An error occurred (BadRequestException) when calling the PutEmailIdentityDkimSigningAttributes operation: 1 validation error detected: Value at 'signingAttributes.domainSigningPrivateKey' failed to satisfy constraint: Member must satisfy regular expression pattern: ^[a-zA-Z0-9+\\/]+={0,2}$", "errorType": "BadRequestException", "requestId": "bd1cff84-dfe9-46d9-951e-bb5478547704", "stackTrace": ["  File \"/var/task/index.py\", line 41, in lambda_handler\n    result = handle_phase_management(event, secret_arn, bucket_name)\n", "  File \"/var/task/index.py\", line 235, in handle_phase_management\n    phase_7_result = execute_phase_7(config, secret_arn, bucket_name)\n", "  File \"/var/task/index.py\", line 453, in execute_phase_7\n    response = sesv2_client.put_email_identity_dkim_signing_attributes(\n", "  File \"/var/lang/lib/python3.13/site-packages/botocore/client.py\", line 602, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.13/site-packages/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/lang/lib/python3.13/site-packages/botocore/client.py\", line 1078, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}