{"errorMessage": "Unknown action: generate_dns_config", "errorType": "ValueError", "requestId": "c2c74eb4-3a5d-4a68-b58d-e9173e382be7", "stackTrace": ["  File \"/var/task/index.py\", line 52, in lambda_handler\n    raise ValueError(f\"Unknown action: {action}\")\n"]}