{"errorMessage": "Command '['openssl', 'genpkey', '-algorithm', 'RSA', '-pkcs8', '-out', '/tmp/tmp9bqofp58/private.pem', '-pkeyopt', 'rsa_keygen_bits:2048']' returned non-zero exit status 1.", "errorType": "CalledProcessError", "requestId": "3dab2c19-d54a-4b71-ae4d-8106c529a576", "stackTrace": ["  File \"/var/task/index.py\", line 44, in lambda_handler\n    result = create_dkim_certificate(secret_arn, bucket_name, dkim_separator)\n", "  File \"/var/task/index.py\", line 594, in create_dkim_certificate\n    subprocess.run([\n", "  File \"/var/lang/lib/python3.13/subprocess.py\", line 577, in run\n    raise CalledProcessError(retcode, process.args,\n"]}