{"errorMessage": "An error occurred (AccessDeniedException) when calling the PutEmailIdentityDkimSigningAttributes operation: User: arn:aws:sts::627642418836:assumed-role/aws-byodmim-prod-dkim-manager-role/aws-byodmim-prod-dkim-manager is not authorized to perform: ses:PutEmailIdentityDkimSigningAttributes on resource: arn:aws:ses:ap-northeast-1:627642418836:identity/goo.ne.jp because no identity-based policy allows the ses:PutEmailIdentityDkimSigningAttributes action", "errorType": "ClientError", "requestId": "73399f27-962e-4bdb-bc76-6db124b158f9", "stackTrace": ["  File \"/var/task/index.py\", line 41, in lambda_handler\n    result = handle_phase_management(event, secret_arn, bucket_name)\n", "  File \"/var/task/index.py\", line 226, in handle_phase_management\n    phase_7_result = execute_phase_7(config, secret_arn, bucket_name)\n", "  File \"/var/task/index.py\", line 413, in execute_phase_7\n    response = sesv2_client.put_email_identity_dkim_signing_attributes(\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 602, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/lang/lib/python3.11/site-packages/botocore/client.py\", line 1078, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}